[profile.default]
src = "src"
out = "out"
libs = ["lib"]
rpc_endpoints = { sepolia = "**", arb-sepolia = "**", zksync-sepolia = "**" }
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    '@ccip/=lib/ccip/',
    '@chainlink-local/=lib/chainlink-local/',
]
